/*
Minhazul Hayat Khan
Website: www.minhazul.com
EWU, Bangladesh
Problem Name: --- Day 8: Resonant Collinearity ---
Problem Link: https://adventofcode.com/2024/day/8
Date : 11 / 12 / 2024
Comment:
*/

#include<bits/stdc++.h>
using namespace std;

vector<string> mat;
map<char, vector<pair<int,int>> > mp;
int boundX,  boundY;

bool insideBound(int x, int y);
set<pair<int,int> > findResonant(vector<pair<int,int> > vec);
set<pair<int,int>> uniq;

int main(){
    long long int a,realSum, totalSum = 0;
    char ch;
    string str;
    while(cin >> str){
        mat.push_back(str);
    }

    for(int i=0;i<mat.size();i++){
        for(int j=0;j<mat[i].size();j++){
            ch = mat[i][j];
            cout << ch << " ";
            if(ch != '.'){
                if(mp.find(ch) == mp.end()){
                    mp[ch] = vector<pair<int,int> >();
                }
                mp[ch].push_back(make_pair(i,j));
            }
        }
        cout << endl;
    }

    boundX = mat.size();
    boundY = mat[0].size();

    for(auto ant: mp){
        vector<pair<int,int> > vec = ant.second;
        auto st = findResonant(vec);
        uniq.insert(st.begin(), st.end());


//            auto st = findResonant(vec);
//            uniq.insert(st.begin(), st.end());
//            for(auto x: st)
//            vec.push_back(make_pair(x.first, x.second));
//
//            auto st1 = findResonant(vec);
//            uniq.insert(st1.begin(), st1.end());

        for(int i=0;i<vec.size();i++){
            uniq.insert(make_pair(vec[i].first, vec[i].second));
        }
    }

    cout << "Total Unique Locations for Antinodes: " << uniq.size() << endl;
    return 0;
}

bool insideBound(int x, int y){
    return (x >=0 && x< boundX && y >=0 && y < boundY);
}

set<pair<int,int> > findResonant(vector<pair<int,int> > vec){
    set<pair<int,int> > st;
    for(int i=0;i<vec.size();i++){
//            cout << ant.first <<": " << vec[i].first << " " << vec[i].second << endl;
        for(int j=i+1;j<vec.size();j++){
            int dx = vec[i].first - vec[j].first;
            int dy = vec[i].second - vec[j].second;

            int cx = vec[i].first;
            int cy = vec[i].second;
            for(int k=0;k<100;k++){
                int x1 = cx + dx;
                int y1 = cy + dy;
                if(insideBound(x1, y1) ){
                    if(mat[x1][y1] == '.'){
                        st.insert(make_pair(x1, y1));
                    }
                }
                cx = x1;
                cy = y1;
            }

            cx = vec[j].first;
            cy = vec[j].second;
            for(int k=0;k<100;k++){
                int x2 = cx - dx;
                int y2 = cy - dy;
                if(insideBound(x2, y2)){
                    if(mat[x2][y2] == '.'){
                        st.insert(make_pair(x2, y2));
                    }
                }
                cx = x2;
                cy = y2;
            }
        }
    }
    return st;
}

/* Answer: 34
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............

*/

/* Answer: 1015
...d............................J.................
......e.............................J.............
..........6............7..........................
........................P7........................
..................................................
.........6........................................
e..........................x.................E....
...G...A.......d...........................o......
.....A.e...........................J......8.......
................6....9.....J.............E.8......
..........d.9.........7..K....E...................
...e.....U....9................x..K...............
......A......O...........P................o.......
......................x..................M..E.....
........................x........p................
........A..................O......................
.......r.f....O.......P9..G.........m.............
u...df..r...............7.........................
.....g.............nXu......N.........K...........
..............l..........0..............p.........
.......lu...................p......o..............
....g..........l........0p..G.....F...............
.....................................8......F.....
...................................C..............
....3................G0......................M....
2...f....g..........3........P......O......F......
g......3.....0....H......................F..M.....
.............c................m...h.....M.........
...........2....l.................................
..U...c......2...........................K........
.D....................r.....f.....................
....................N.............................
.U..............h.................................
...a.............u..............C.................
c...Uj....a..6...H...................R............
...3....j................H...............m........
.......................5.......C..........4....m..
......................H.........R......N....X.....
.........h..2.................R................N..
.......................r...........q...n..........
.....c..............5.............................
..a..h....D.................................n.....
......qk..................D............1.....X....
.k..................................q.............
..k..........a.............L................1....4
......k..........RQ..5.L.j..1..................4..
..................................................
..............L.....................oX............
........Q.............L.........n.................
...........Q.D........5..........1............4...

*/
