#include <stdio.h>
#include <stdlib.h>
#include "id3.c"

char *dataset[] =
{
// 	attr 1		attr 2		attr 3		attr 4		classes1, 1, 1, 1, 1, 2,
"Sunny","Hot","High","Weak","No",
"Sunny","Hot","High","Strong","No",
"Overcast","Hot","High","Weak","Yes",
"Rain","Mild","High","Weak","Yes",
"Rain","Cool","Normal","Weak","Yes",
"Rain","Cool","Normal","Strong","No",
"Overcast","Cool","Normal","Strong","Yes",
"Sunny","Mild","High","Weak","No",
"Sunny","Cool","Normal","Weak","Yes",
"Rain","Mild","Normal","Weak","Yes",
"Sunny","Mild","Normal","Strong","Yes",
"Overcast","Mild","High","Strong","Yes",
"Overcast","Hot","Normal","Weak","Yes",
"Rain","Mild","High","Strong","No"
/*

"FEMALE",      "TOWN      ",        "YES",     	"0",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "NO ",     	"0",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     	"1",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "YES",     	"1",     "YES_CAR",
"MALE  ",      "RURAL     ",        "YES",     	"0",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "2",     "NO_CAR ",
"FEMALE",      "SUBURBAN  ",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "2",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     "2",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "NO ",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "NO ",     "2",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "YES",     "1",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "NO ",     "3",     "YES_CAR",
"MALE  ",      "RURAL     ",        "YES",     "1",     "NO_CAR ",
"FEMALE",      "RURAL     ",        "YES",     "2",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "YES",     "2",     "NO_CAR ",
"MALE  ",      "SUBURBAN  ",        "YES",     "1",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "NO ",     "3",     "YES_CAR",
"MALE  ",      "SUBURBAN  ",        "NO ",     "0",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "2",     "NO_CAR ",
"MALE  ",      "RURAL     ",        "YES",     "3",     "YES_CAR",
"FEMALE",      "RURAL     ",        "NO ",     "0",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "0",     "YES_CAR",
"FEMALE",      "SUBURBAN  ",        "NO ",     "2",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"MALE  ",      "TOWN      ",        "NO ",     "2",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "NO ",     "2",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "2",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "NO ",     "1",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "NO ",     "2",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "NO ",     "2",     "YES_CAR",
"FEMALE",      "RURAL     ",        "YES",     "2",     "YES_CAR",
"MALE  ",      "TOWN      ",        "NO ",     "2",     "YES_CAR",
"MALE  ",      "TOWN      ",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     "1",     "NO_CAR ",
"MALE  ",      "SUBURBAN  ",        "NO ",     "1",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "RURAL     ",        "NO ",     "3",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "NO ",     "0",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "NO ",     "1",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "1",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "NO ",     "1",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "2",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "NO ",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "NO ",     "2",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "NO ",     "0",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "NO ",     "2",     "NO_CAR ",
"FEMALE",      "RURAL     ",        "YES",     "2",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "3",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "NO ",     "0",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "3",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "2",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "NO ",     "2",     "YES_CAR",
"FEMALE",      "RURAL     ",        "NO ",     "2",     "YES_CAR",
"FEMALE",      "TOWN      ",        "NO ",     "0",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "1",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "2",     "YES_CAR",
"FEMALE",      "TOWN      ",        "NO ",     "3",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "NO ",     "3",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "1",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "1",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "1",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "NO ",     "0",     "YES_CAR",
"MALE  ",      "SUBURBAN  ",        "YES",     "0",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "2",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     "1",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "NO ",     "2",     "NO_CAR ",
"FEMALE",      "RURAL     ",        "NO ",     "0",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "2",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "1",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     "2",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "NO ",     "2",     "NO_CAR ",
"FEMALE",      "RURAL     ",        "YES",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "1",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "2",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"MALE  ",      "TOWN      ",        "NO ",     "0",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "1",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     "3",     "YES_CAR",
"MALE  ",      "RURAL     ",        "YES",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "NO ",     "0",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "2",     "YES_CAR",
"MALE  ",      "TOWN      ",        "NO ",     "2",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "3",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"MALE  ",      "TOWN      ",        "NO ",     "2",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "1",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "YES",     "2",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "3",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "NO ",     "0",     "YES_CAR",
"FEMALE",      "RURAL     ",        "YES",     "3",     "YES_CAR",
"MALE  ",      "RURAL     ",        "NO ",     "2",     "NO_CAR ",
"FEMALE",      "RURAL     ",        "YES",     "1",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "1",     "NO_CAR ",
"FEMALE",      "RURAL     ",        "NO ",     "1",     "NO_CAR ",
"MALE  ",      "RURAL     ",        "NO ",     "3",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "2",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "YES",     "0",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     "3",     "YES_CAR",
"FEMALE",      "RURAL     ",        "NO ",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "NO ",     "2",     "NO_CAR ",
"MALE  ",      "RURAL     ",        "YES",     "3",     "NO_CAR ",
"FEMALE",      "SUBURBAN  ",        "NO ",     "2",     "YES_CAR",
"FEMALE",      "SUBURBAN  ",        "YES",     "0",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "2",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "1",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "2",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "NO ",     "0",     "NO_CAR ",
"FEMALE",      "RURAL     ",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "NO ",     "1",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "3",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "YES",     "1",     "YES_CAR",
"MALE  ",      "TOWN      ",        "YES",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "1",     "NO_CAR ",
"MALE  ",      "SUBURBAN  ",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     "2",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "NO ",     "2",     "NO_CAR ",
"MALE  ",      "RURAL     ",        "YES",     "0",     "YES_CAR",
"FEMALE",      "SUBURBAN  ",        "YES",     "3",     "YES_CAR",
"MALE  ",      "RURAL     ",        "YES",     "1",     "YES_CAR",
"MALE  ",      "TOWN      ",        "NO ",     "2",     "YES_CAR",
"MALE  ",      "TOWN      ",        "YES",     "2",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "1",     "NO_CAR ",
"MALE  ",      "RURAL     ",        "NO ",     "2",     "YES_CAR",
"FEMALE",      "SUBURBAN  ",        "YES",     "2",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     "0",     "YES_CAR",
"MALE  ",      "RURAL     ",        "YES",     "2",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "YES",     "1",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "2",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "NO ",     "3",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "NO ",     "1",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "RURAL     ",        "YES",     "1",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "NO ",     "1",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "NO ",     "1",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "NO ",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "2",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "3",     "YES_CAR",
"MALE  ",      "RURAL     ",        "YES",     "1",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "2",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "NO ",     "0",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     "0",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "2",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "1",     "NO_CAR ",
"MALE  ",      "RURAL     ",        "NO ",     "0",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "NO ",     "0",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "2",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "NO ",     "0",     "YES_CAR",
"MALE  ",      "RURAL     ",        "YES",     "1",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "YES",     "1",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "2",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "SUBURBAN  ",        "YES",     "2",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "1",     "YES_CAR",
"FEMALE",      "RURAL     ",        "YES",     "3",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"MALE  ",      "SUBURBAN  ",        "YES",     "2",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "1",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "NO ",     "0",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "2",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "NO ",     "2",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     "1",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "NO ",     "3",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "1",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "NO ",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "NO ",     "0",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "NO ",     "0",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "NO ",     "0",     "YES_CAR",
"MALE  ",      "TOWN      ",        "YES",     "1",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"MALE  ",      "TOWN      ",        "NO ",     "1",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "SUBURBAN  ",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "SUBURBAN  ",        "YES",     "0",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "3",     "YES_CAR",
"MALE  ",      "TOWN      ",        "NO ",     "0",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "NO ",     "2",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "2",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "1",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "RURAL     ",        "YES",     "3",     "NO_CAR ",
"FEMALE",      "RURAL     ",        "NO ",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "2",     "YES_CAR",
"MALE  ",      "TOWN      ",        "NO ",     "0",     "NO_CAR ",
"MALE  ",      "RURAL     ",        "NO ",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "NO ",     "0",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "NO ",     "1",     "NO_CAR ",
"MALE  ",      "SUBURBAN  ",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "YES",     "0",     "YES_CAR",
"FEMALE",      "RURAL     ",        "NO ",     "3",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "NO ",     "1",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "NO ",     "2",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "2",     "NO_CAR ",
"FEMALE",      "RURAL     ",        "YES",     "2",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"FEMALE",      "RURAL     ",        "YES",     "2",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "NO ",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "1",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"MALE  ",      "RURAL     ",        "YES",     "2",     "YES_CAR",
"MALE  ",      "SUBURBAN  ",        "NO ",     "0",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "NO ",     "3",     "YES_CAR",
"MALE  ",      "RURAL     ",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     "3",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     "3",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "NO ",     "0",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "YES",     "1",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "2",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "YES",     "1",     "NO_CAR ",
"FEMALE",      "RURAL     ",        "NO ",     "3",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "NO ",     "0",     "YES_CAR",
"FEMALE",      "SUBURBAN  ",        "NO ",     "2",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "YES",     "2",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "NO ",     "3",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "NO ",     "0",     "NO_CAR ",
"MALE  ",      "SUBURBAN  ",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "YES",     "1",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "NO ",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "1",     "YES_CAR",
"MALE  ",      "TOWN      ",        "NO ",     "0",     "YES_CAR",
"FEMALE",      "SUBURBAN  ",        "NO ",     "0",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "YES",     "0",     "YES_CAR",
"MALE  ",      "TOWN      ",        "NO ",     "3",     "YES_CAR",
"FEMALE",      "SUBURBAN  ",        "NO ",     "2",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "NO ",     "0",     "YES_CAR",
"MALE  ",      "TOWN      ",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "1",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"MALE  ",      "RURAL     ",        "YES",     "0",     "YES_CAR",
"FEMALE",      "SUBURBAN  ",        "NO ",     "1",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     "1",     "YES_CAR",
"FEMALE",      "RURAL     ",        "NO ",     "0",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     "1",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "1",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "1",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "3",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "3",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "1",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "3",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "1",     "NO_CAR ",
"FEMALE",      "RURAL     ",        "YES",     "1",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "NO ",     "0",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "NO ",     "0",     "YES_CAR",
"MALE  ",      "RURAL     ",        "YES",     "2",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     "0",     "YES_CAR",
"FEMALE",      "RURAL     ",        "NO ",     "2",     "YES_CAR",
"MALE  ",      "RURAL     ",        "YES",     "2",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "NO ",     "2",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "1",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "RURAL     ",        "YES",     "3",     "NO_CAR ",
"FEMALE",      "RURAL     ",        "NO ",     "3",     "NO_CAR ",
"FEMALE",      "RURAL     ",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "NO ",     "2",     "YES_CAR",
"MALE  ",      "RURAL     ",        "NO ",     "0",     "YES_CAR",
"MALE  ",      "TOWN      ",        "NO ",     "2",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "NO ",     "1",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "NO ",     "1",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "NO ",     "2",     "YES_CAR",
"FEMALE",      "RURAL     ",        "NO ",     "2",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "0",     "YES_CAR",
"MALE  ",      "RURAL     ",        "NO ",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "NO ",     "2",     "YES_CAR",
"FEMALE",      "TOWN      ",        "NO ",     "1",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "NO ",     "2",     "NO_CAR ",
"MALE  ",      "SUBURBAN  ",        "NO ",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "NO ",     "2",     "YES_CAR",
"MALE  ",      "RURAL     ",        "YES",     "0",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "1",     "YES_CAR",
"MALE  ",      "TOWN      ",        "NO ",     "0",     "NO_CAR ",
"MALE  ",      "SUBURBAN  ",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "NO ",     "0",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "1",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "RURAL     ",        "NO ",     "1",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "YES",     "3",     "NO_CAR ",
"FEMALE",      "RURAL     ",        "YES",     "3",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "2",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "SUBURBAN  ",        "YES",     "2",     "NO_CAR ",
"FEMALE",      "SUBURBAN  ",        "YES",     "1",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     "1",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "2",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "1",     "YES_CAR",
"MALE  ",      "SUBURBAN  ",        "YES",     "2",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "SUBURBAN  ",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "RURAL     ",        "YES",     "1",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "RURAL     ",        "YES",     "2",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "1",     "NO_CAR ",
"MALE  ",      "RURAL     ",        "YES",     "0",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "NO ",     "1",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "NO ",     "0",     "YES_CAR",
"MALE  ",      "TOWN      ",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "RURAL     ",        "NO ",     "1",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "NO ",     "1",     "YES_CAR",
"FEMALE",      "SUBURBAN  ",        "YES",     "0",     "YES_CAR",
"FEMALE",      "RURAL     ",        "YES",     "2",     "NO_CAR ",
"FEMALE",      "SUBURBAN  ",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "RURAL     ",        "NO ",     "0",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "NO ",     "3",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "1",     "YES_CAR",
"FEMALE",      "TOWN      ",        "NO ",     "2",     "YES_CAR",
"MALE  ",      "TOWN      ",        "YES",     "3",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     "2",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "YES",     "1",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "2",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "NO ",     "1",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"MALE  ",      "TOWN      ",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "3",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "NO ",     "2",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "NO ",     "0",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "SUBURBAN  ",        "YES",     "2",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"FEMALE",      "TOWN      ",        "NO ",     "1",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "NO ",     "2",     "NO_CAR ",
"MALE  ",      "SUBURBAN  ",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "3",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "NO ",     "0",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "2",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "1",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "YES",     "1",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "NO ",     "3",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "NO ",     "0",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "NO ",     "1",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "NO ",     "0",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "NO ",     "0",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "3",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "2",     "YES_CAR",
"FEMALE",      "SUBURBAN  ",        "NO ",     "0",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "3",     "YES_CAR",
"MALE  ",      "RURAL     ",        "YES",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "2",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "NO ",     "1",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     "0",     "YES_CAR",
"FEMALE",      "RURAL     ",        "NO ",     "0",     "NO_CAR ",
"MALE  ",      "RURAL     ",        "NO ",     "3",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "NO ",     "0",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "3",     "NO_CAR ",
"MALE  ",      "SUBURBAN  ",        "YES",     "3",     "YES_CAR",
"MALE  ",      "SUBURBAN  ",        "NO ",     "1",     "NO_CAR ",
"MALE  ",      "SUBURBAN  ",        "NO ",     "0",     "NO_CAR ",
"FEMALE",      "SUBURBAN  ",        "YES",     "1",     "YES_CAR",
"MALE  ",      "SUBURBAN  ",        "YES",     "2",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "NO ",     "1",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "NO ",     "0",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "NO ",     "2",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"FEMALE",      "SUBURBAN  ",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "RURAL     ",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "NO ",     "1",     "NO_CAR ",
"MALE  ",      "RURAL     ",        "YES",     "1",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "2",     "YES_CAR",
"MALE  ",      "TOWN      ",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "NO ",     "1",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "1",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"MALE  ",      "TOWN      ",        "NO ",     "1",     "YES_CAR",
"FEMALE",      "RURAL     ",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "YES",     "3",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "2",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "1",     "YES_CAR",
"MALE  ",      "RURAL     ",        "NO ",     "2",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "YES",     "1",     "YES_CAR",
"MALE  ",      "TOWN      ",        "NO ",     "0",     "YES_CAR",
"FEMALE",      "RURAL     ",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"MALE  ",      "TOWN      ",        "NO ",     "2",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "NO ",     "1",     "YES_CAR",
"FEMALE",      "SUBURBAN  ",        "YES",     "1",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "1",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "1",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"FEMALE",      "RURAL     ",        "YES",     "0",     "YES_CAR",
"MALE  ",      "TOWN      ",        "NO ",     "0",     "YES_CAR",
"FEMALE",      "RURAL     ",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "RURAL     ",        "YES",     "0",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "YES",     "2",     "NO_CAR ",
"MALE  ",      "RURAL     ",        "YES",     "3",     "YES_CAR",
"FEMALE",      "RURAL     ",        "NO ",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "3",     "YES_CAR",
"MALE  ",      "TOWN      ",        "NO ",     "0",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "NO ",     "0",     "NO_CAR ",
"FEMALE",      "RURAL     ",        "NO ",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "NO ",     "0",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "0",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "SUBURBAN  ",        "NO ",     "1",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     "1",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"FEMALE",      "SUBURBAN  ",        "YES",     "0",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"FEMALE",      "RURAL     ",        "YES",     "2",     "YES_CAR",
"MALE  ",      "TOWN      ",        "NO ",     "0",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "2",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "SUBURBAN  ",        "NO ",     "3",     "NO_CAR ",
"MALE  ",      "SUBURBAN  ",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "NO ",     "3",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "2",     "YES_CAR",
"FEMALE",      "TOWN      ",        "NO ",     "0",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "NO ",     "1",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "2",     "NO_CAR ",
"MALE  ",      "RURAL     ",        "NO ",     "1",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     "2",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "NO ",     "1",     "YES_CAR",
"MALE  ",      "RURAL     ",        "YES",     "2",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "NO ",     "2",     "YES_CAR",
"MALE  ",      "RURAL     ",        "NO ",     "0",     "NO_CAR ",
"MALE  ",      "RURAL     ",        "YES",     "0",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "1",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "RURAL     ",        "YES",     "1",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "YES",     "3",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "2",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "1",     "YES_CAR",
"FEMALE",      "TOWN      ",        "NO ",     "1",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "NO ",     "0",     "NO_CAR ",
"FEMALE",      "RURAL     ",        "YES",     "3",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "NO ",     "2",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "NO ",     "0",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "NO ",     "0",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "YES",     "0",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "3",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "NO ",     "1",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "0",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "NO ",     "0",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "1",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "0",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "SUBURBAN  ",        "NO ",     "0",     "YES_CAR",
"MALE  ",      "SUBURBAN  ",        "NO ",     "2",     "NO_CAR ",
"FEMALE",      "RURAL     ",        "YES",     "2",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "3",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "YES",     "0",     "YES_CAR",
"FEMALE",      "RURAL     ",        "NO ",     "3",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "NO ",     "0",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "1",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "NO ",     "0",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     "1",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "NO ",     "3",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "3",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "2",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "2",     "YES_CAR",
"MALE  ",      "SUBURBAN  ",        "NO ",     "3",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "YES",     "0",     "YES_CAR",
"MALE  ",      "SUBURBAN  ",        "YES",     "0",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "1",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "NO ",     "2",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "NO ",     "1",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "2",     "NO_CAR ",
"MALE  ",      "RURAL     ",        "YES",     "1",     "YES_CAR",
"MALE  ",      "SUBURBAN  ",        "YES",     "1",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "NO ",     "1",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "NO ",     "1",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"FEMALE",      "TOWN      ",        "NO ",     "1",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "NO ",     "1",     "NO_CAR ",
"FEMALE",      "RURAL     ",        "NO ",     "2",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "1",     "YES_CAR",
"MALE  ",      "RURAL     ",        "YES",     "2",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "2",     "YES_CAR",
"MALE  ",      "SUBURBAN  ",        "YES",     "1",     "YES_CAR",
"MALE  ",      "RURAL     ",        "YES",     "1",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "NO ",     "0",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "NO ",     "0",     "YES_CAR",
"MALE  ",      "SUBURBAN  ",        "YES",     "2",     "YES_CAR",
"MALE  ",      "RURAL     ",        "YES",     "1",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "1",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "1",     "YES_CAR",
"MALE  ",      "SUBURBAN  ",        "YES",     "3",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "2",     "YES_CAR",
"FEMALE",      "SUBURBAN  ",        "YES",     "0",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "3",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "2",     "YES_CAR",
"FEMALE",      "RURAL     ",        "YES",     "1",     "YES_CAR",
"MALE  ",      "RURAL     ",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "SUBURBAN  ",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "SUBURBAN  ",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "NO ",     "1",     "NO_CAR ",
"FEMALE",      "SUBURBAN  ",        "NO ",     "0",     "NO_CAR ",
"FEMALE",      "RURAL     ",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "NO ",     "1",     "NO_CAR ",
"MALE  ",      "SUBURBAN  ",        "YES",     "0",     "YES_CAR",
"MALE  ",      "TOWN      ",        "YES",     "0",     "YES_CAR",
"MALE  ",      "TOWN      ",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "2",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "NO ",     "1",     "YES_CAR",
"FEMALE",      "RURAL     ",        "NO ",     "3",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "SUBURBAN  ",        "NO ",     "2",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     "2",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"MALE  ",      "TOWN      ",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "YES",     "1",     "YES_CAR",
"MALE  ",      "TOWN      ",        "YES",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "NO ",     "0",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "YES",     "0",     "YES_CAR",
"MALE  ",      "SUBURBAN  ",        "YES",     "2",     "YES_CAR",
"MALE  ",      "TOWN      ",        "YES",     "2",     "YES_CAR",
"FEMALE",      "TOWN      ",        "NO ",     "3",     "NO_CAR ",
"FEMALE",      "RURAL     ",        "NO ",     "2",     "YES_CAR",
"MALE  ",      "TOWN      ",        "YES",     "1",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "NO ",     "3",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "1",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "NO ",     "1",     "YES_CAR",
"MALE  ",      "RURAL     ",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "SUBURBAN  ",        "YES",     "1",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "NO ",     "2",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "SUBURBAN  ",        "YES",     "2",     "NO_CAR ",
"FEMALE",      "RURAL     ",        "YES",     "3",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "NO ",     "2",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "NO ",     "0",     "YES_CAR"

*/
};


int main()
{
    int result = 0;


    result = id3tree_create( 	dataset,			// puntatore al database
								5,					// totale colonne ( attributi + classi )
								14,					// totale samples nel database
								"outlook",			// etichetta per attributo 1
								"temp",		// etichetta per attributo 2
								"humidity",			// etichetta per attributo 3
								"wind",				// etichetta per attributo 4
								"playtennis",			// etichetta per classi
								NULL				// terminatore
							);
    //printf( "Esito: %d\n", result );


    return 0;
}
